apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "fullname" .}}
  labels:
    release: {{ .Release.Name | quote }}
    app: {{template "fullname" .}}
    heritage: {{.Release.Service | quote }}
data:
  deis.builder: {{ .Values.deisBuilder }}
