kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{template "fullname" .}}
  annotations:
    volume.beta.kubernetes.io/storage-class: "default"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{default .Values.storageSize "100Gi"}}

