kind: Secret
apiVersion: v1
metadata:
  name: {{template "proxyname" .}}
type: Opaque
data:
  cert.pem: {{ .Files.Get "cert.pem" | b64enc | quote }}
  key.pem: {{ .Files.Get "key.pem" | b64enc | quote }}
  dhparam: {{ .Files.Get "dhparam" | b64enc | quote }}
  htpasswd: {{ .Files.Get "htpasswd" | b64enc | quote }}
