kind: Secret
apiVersion: v1
metadata:
  name: {{template "fullname" .}}
type: Opaque
data:
  jenkins-deis-conf.json: {{ .Files.Get "jenkins-deis-conf.json" | b64enc | quote }}
  jenkins-ssh-key: {{ .Files.Get "id_rsa-deis" | b64enc | quote }}
